### ISSUE TITLE
Advertisement Deserialization Bug

### ISSUE THREAD

**Issue by sergiomr88** [aconno/Sensorics#109]
**Description**
Advertisement deserialization stops working if the app is killed in the background.

**Comment by borna-mdn** [comment]
@Nicba1010 
Test this issue by killing app from different scenarios and see if there is some faulty behaviour.

If there are issues, recycle this issue to solve them and close this one.

If there are no issues, close this one.

**Comment by grubelic** [comment]
@borna-mdn 
When user leaves the app using the back navigation and/or removes it from the Recents screen, deserialization keeps working normally.

After killing / force stopping the app, deserialization stops working until it is manually started again. That is expected behaviour (there are no issues).
