### ISSUE TITLE
MainActivity snackbar hides FAB

### ISSUE THREAD

**Issue by sergiomr88** [aconno/Sensorics#62]
**Description**
Current app has a fab which will be hidden when the settings option is shown.

**To Reproduce**
1. Open the app without permissions.
2. Click on start scanning.
3. Deny the permission.
4. Settings snackbar hides the fab.

**Expected behavior**
Fab should move up with the snackbar.

**Desktop**
All versions.

**Smartphone**
All versions.

**Additional context**
NA

**Comment by SerhatSurguvec** [comment]
To solve the issue FAB should be a direct child of CoordinatorLayout. It will affect MainActivity and Fragments. Since it is not urgent. We will do it when we have time.

Solutions: 
1- Add CoordinatorLayout as a parent layout in MainActivity. And Add FAB Button to MainActivity. Use FAB through MainActivity in Fragments.
2- Add CoordinatorLayout as a parent layout in Fragments that contains FAB. Show Snackbars in Fragments.

**Comment by SerhatSurguvec** [comment]
It is being fixed in view-pager branch
