### ISSUE TITLE
Refactor Outcome

### ISSUE THREAD

**Issue by borna-mdn** [aconno/Sensorics#71]
**Problem**
Outcomes are terribly implemented. The code is very rigid.

**Preferred Solution**
Refactor Outcome class, and all dependent components, in more SOLID way.

**Comment by grubelic** [comment]
That has been refactored in commits ["Extract Outcome class in separate file"](https://github.com/aconno/Sensorics/commit/c89824f0b51c0b7768e5d3df11f3eaf41717a068) and ["Implement action details screen"](https://github.com/aconno/Sensorics/commit/68f61b638b2ce320a6b52fd7d38a07f92cfada38) and it was pulled from pull request #72 a couple of days after this issue was made. Is further refactoring needed?
